[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Akira Ueda <ue@gol.com>"]
edition = "2018"

[dependencies]
actix-web = "=4.0.0-beta.5"
actix-http = "=3.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
